language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://lmayo.pactflow.io
  # PACT_BROKER_TOKEN is encrypted below
  - secure: "Yp49UucNIDR072Zk1YW23BQIw17gtS139gPbDXtcBpQ7XpnzAGNQdk/f73qdpjd8Rpvoyz/8l76GaSRkGiZQqjQfDsrIHLnG1wVDUn4PF1/6kIneVNpxOp78JUZN8UH8+jUCcJaZL4bMUie8yJFYUqEAyuiJgq9gtftYj7YUy3Teueqi+c8Yx2abOhirv5F2YUOLvU/O9MSt2r+L0Vs3P6inoBg4UzlrhqlgNEK3rL2Q6wq5fArFumeSR6FXIzYkV0ObuspB+7zjLdvR3m2LfGZ8c32/5yWUEBP+273zIXwKbtnWVUZe5wlBcdNIMCTHN6Z/0JBQ1c45QgSq14g1hyewFo7sT1mYNXJOfbO4GYuu5+W5xcIwqnEuapUGV+rVP4Xt84aJMc3IaVRo1y1Qi9oLA4NAzhfYBuiUMAYb+nneo9OpL2wefr1fSAAqQH/uuGzved43GrFaOv8IHkCd/4YkdOGOWLxsGBXBKYaGsKhKSEwMkmYH8sAXCFWLbpaLvVwPKU19qtKMbkf+rnzMXxYGO1abj1Oo7NflSdSFh2ibz7ZMcZfKMAHFO/HuzeVasIMwyVqQjietnVq1y3ce3VhRVTKlv3xvrho4e2HzNx6jNTTJ1i/nYY3FiAJSC6LYHl2G1KsElXyJaV7K0CqIct8o8yBzXUgx2wsub//bXEQ="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
